compiler: clang

script:
  - mkdir travis-build
  - cd travis-build
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - ./emsdk install latest
  - ./emsdk activate latest
  - source ./emsdk_env.sh
  - cd ..
  - source /etc/environment
  - npm install -g gulp
  - npm install
  - gulp
